export default[
    {
        "userFormationSelected" : "4-2-3-1",
        "userTeamName" : "Serie A",
        "userTeamRating" : "83",
        "oppSquad" : [
            "La Liga", "Ligue 1"
        ],
        "oppFormationSelected" : "4-1-2-1-2(2)",
        "oppName" : "kritikos8",
        "oppTeamName" : "Undftd Crks",
        "oppTeamRating" : "85",
        "userGoals" : "2",
        "oppGoals" : "1",
        "userShots" : "10",
        "oppShots" : "5",
        "userShotsOnGoal" : "6",
        "oppShotsOnGoal" : "4",
        "userPossession" : "54",
        "oppPossession" : 46,
        "userTackles" : "7",
        "oppTackles" : "6",
        "userCorners" : "3",
        "oppCorners" : "1",
        "userPassAccuracy" : "88",
        "oppPassAccuracy" : "82",
        "rageQuitChecked" : false,
        "rageQuitMinute" : "",
        "disconnectedFromEA" : false,
        "matchGeneralNotes" : "First game!",
        "userPenScore" : "",
        "oppPenScore" : "",
        "userWon" : true
    }, {
        "userFormationSelected" : "4-4-1-1",
        "userTeamName" : "La Liga",
        "userTeamRating" : "82",
        "oppSquad" : ["Bundes"],
        "oppFormationSelected" : "4-3-3",
        "oppName" : "fifaIsFun",
        "oppTeamName" : "Fake Game",
        "oppTeamRating" : "86",
        "userGoals" : "5",
        "oppGoals" : "1",
        "userShots" : "10",
        "oppShots" : "2",
        "userShotsOnGoal" : "7",
        "oppShotsOnGoal" : "1",
        "userPossession" : "58",
        "oppPossession" : 42,
        "userTackles" : "10",
        "oppTackles" : "3",
        "userCorners" : "1",
        "oppCorners" : "1",
        "userPassAccuracy" : "91",
        "oppPassAccuracy" : "85",
        "rageQuitChecked" : false,
        "rageQuitMinute" : "",
        "disconnectedFromEA" : false,
        "matchGeneralNotes" : "2nd Game",
        "userPenScore" : "",
        "oppPenScore" : "",
        "userWon" : true
    }
];